### ISSUE TITLE
Pass additional information to the server selector from the client

### ISSUE THREAD

**Issue by aminjam** [aldeed/meteor-tabular#86] opened 2015-02-28 21:55 UTC
Is it possible to have a server side filter/selector that's other than `userId`? I have the data stored in a `Session`, but not sure how to pass it back to the server for security other than the basic `userId`.
```
TabularTables.Books = new Tabular.Table({
  // other properties...
  selector: function( userId ) {
    return { documentOwner: userId }
  }
});
```
 Ideally, it would be great if we can pass in the collection at the time of rendering the template, something like.

```
{{> tabular table=TabularTables.Books data=.}}
``` 
where `.` represents the the data array of elements passed by iron router.

**Comment by aldeed** [comment] 2015-03-02 03:01
You should use the client side selector. It is merged with the server selector.

**Comment by aminjam** [comment] 2015-03-03 22:28
Yes, that's what I am doing right now, but for security reason, I wanted to be able to filter on the server side.

**Comment by aldeed** [comment] 2015-03-04 14:30
How would it increase security if the data for the selector is sent from the client anyway? Is the idea that you would check what is sent and ensure it is valid for the current user? We could probably have a way to provide extra client data to the server selector function, but I'd like to have a full picture of a valid use case before doing it.

**Comment by Framnk** [comment] 2015-03-07 22:13
Hi, I have a similar need to pass a parameter to the server-side publish for validation.  I'm using the Roles package and I need to verify that a user has a certain role for a specific role group that I'd like to pass to the publish when subscribing.  While I can check the roles for userId I don't have enough information without being able to pass the role group I am checking for as well.

**Comment by dovrosenberg** [comment] 2015-03-30 00:29
@aminjam, I've addressed a similar problem by recreating the table from the client side when needed.  Specifically, I use a template helper to generate the TabularTable passed into tabular.  The helper generates a new TabularTable as needed (make sure to do that in common code), and each can have it's own server-side selector.  

After the changes I made in #117, the only obstacle I've discovered is that the new filters aren't recognized if you reuse a table name (because the server-side publish looks up the table information by name).  Not sure if that's expected behavior or not.  For me, it was easy enough to generate unique names for each new selector I needed (I used the value in the selector), though I suppose that could create a memory issue depending on the number of tables created...

**Comment by petrometro** [comment] 2015-03-30 00:47
This method has worked for me-
```
	selector : function(userId){
		var sel = {};
		if(Meteor.isServer){
			var user = Meteor.users.findOne(userId);
			if(user && user.serverOnlyProperty) sel.serverOnlyProperty = user.serverOnlyProperty;
		}
		return sel;
	}
```

**Comment by aldeed** [comment] 2015-09-11 12:56
I'd still like to see full code for an example need for this. All the described cases so far seem like they could be handled another way, but I'm probably just not understanding.

**Comment by allenfuller** [comment] 2015-12-20 03:35
Perhaps this fits with the current implementation, but I'm trying to limit documents sent to the server in a multi-tenant environment based on a custom user.profile field "currentOrg" (the organization the user is currently logged into). For obvious security reasons, I don't want any documents that don't belong to that organization sent to the client.

Here's my template code:
```
{{> tabular table=TabularTables.Contacts selector=selector class="table table-striped table-bordered table-condensed"}}
```
Here's my current helper, which includes a client-side selector:
```
Template.contactList.helpers({
  selector: function () {
    var currentOrg = Meteor.user().profile.currentOrg[0];
    return {orgId: currentOrg};
  },
  tableSettings: function () {
    return {
      collection: 'contactTable',
      rowsPerPage: 10,
      showFilter: true,
      fields: [
        {
          key: 'firstName',
          label: 'First Name'
        },
        {
          key: 'lastName',
          label: 'Last Name',
          sortOrder: 0,
          sortDirection: 'ascending' 
        },
        {
          key: 'organizations.0.name',
          label: 'Organization'
        },
        { 
          key: 'emails.0.email',
          label: 'Email',
          tmpl: Template.contactListEmail
        },
        {
          label: 'Actions',
          tmpl: Template.contactListActions
        }
      ]
    };
  }
});
```
And finally, here's the tabular.js file:
```
TabularTables = {};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Contacts = new Tabular.Table({
  name: "contactTable",
  collection: Contacts,
  columns: [
    {data: 'firstName', title: "First Name"},
    {data: 'lastName', title: "Last Name"},
    {data: 'company.0.name', title: "Company"},
    {data: 'emails.0.email', title: "Email", tmpl: Meteor.isClient && Template.contactListEmail},
    {title: "Actions", tmpl: Meteor.isClient && Template.contactListActions}
  ]
});
```
I would like to move the selector to the tabular.js function so the filter happens on the publication, not the subscription. Maybe I'm just calling it wrong, but that's one use case where I'd like to pass something other than userId to the selector.

**Comment by aldeed** [comment] 2016-01-08 05:11
@allenfuller `changeSelector` function should work for you. See https://github.com/aldeed/meteor-tabular#modifying-the-selector

**Closed by aldeed** 2016-01-08 05:11 UTC
Labels: enhancement, needs reproduction

**Comment by allenfuller** [comment] 2016-01-08 05:41
Thanks @aldeed! I'll tinker with `changeSelector`...
