### ISSUE TITLE
[bug?] ordering happens on per-page basis, not for entire dataset.

### ISSUE THREAD

**Issue by ghost** [aldeed/meteor-tabular#275] opened 2016-02-20 20:28 UTC
Not sure if maybe I'm doing something wrong, but the tables that TabularTables makes sort based only on the items of the currently visible page. The expected behavior is that clicking on a header to change ordering causes all items in the data set to be re-ordered. For example, something on page 1 would go to the last page, and something on the last page would go to page 1. 

Maybe there can be two buttons, one for ordering on the current page, and one for ordering the entire dataset (the latter is more useful IMO).

**Comment by Ossip** [comment] 2016-03-08 18:56
Do you mean sorting by clicking on column headers? That works for me - it sorts from whole data set

**Comment by trusktr-goin** [comment] 2016-03-18 06:55
Interesting. Not the case for me, but I have no public repro right now.

**Comment by srinivasdamam** [comment] 2016-03-25 06:03
@trusktr-goin did you found the solution for this?

**Comment by trusktr** [comment] 2016-03-26 04:29
@srinivasdamam Hi Srinivas. :)

No, not yet.

**Comment by aldeed** [comment] 2016-10-30 22:32
Closing this. If someone experiences this and has a reproduction, submit a new issue.

**Closed by aldeed** 2016-10-30 22:32 UTC
