### ISSUE TITLE
Problem search with "date type of field"?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-tabular#193] opened 2015-08-22 09:45 UTC
I have `Date` field.
Ex: `ISODate("2015-08-22T00:00:00.000+0000")`.
But I can't search with this.
Please help m.

**Comment by aldeed** [comment] 2015-09-02 17:39
Closing as duplicate of #121. Not yet possible.

**Closed by aldeed** 2015-09-02 17:39 UTC
