### ISSUE TITLE
Bug? No sorting with collection helpers

### ISSUE THREAD

**Issue by obiwarn** [aldeed/meteor-tabular#151] opened 2015-05-26 21:26 UTC
I use yogiben:admin (which uses tabular).

When I add a collection helper row, this row is not sortable nor searchable. 
Not sure if this is a tabular bug or an admin bug.

**Comment by brylie** [comment] 2015-06-28 15:50
This may be a feature request.

**Comment by brylie** [comment] 2015-06-28 16:06
Possible duplicate of #114

**Comment by aldeed** [comment] 2015-07-14 18:41
See https://github.com/aldeed/meteor-tabular/issues/162#issuecomment-121276002

**Closed by aldeed** 2015-07-14 18:41 UTC

**Comment by brylie** [comment] 2015-10-30 07:30
This is an important feature for usability and 'robustness'. In effect, users will not differentiate between columns created by collection helpers, and may need to sort based on that data.

**Comment by obiwarn** [comment] 2015-10-30 10:30
Yes. Right now we add a "(NO SORT)" label to these columns which is really sad.
