### ISSUE TITLE
Tables not changing when navigating to new route

### ISSUE THREAD

**Issue by ababra** [aldeed/meteor-tabular#94] opened 2015-03-03 03:28 UTC
Here's my route.js (using the latest version of Iron Router);
````
Router.route('/orders', {
  name: 'orders',
  data: {
    datatable: TabularTables.Orders
  }
});

Router.route('/venues', {
  name: 'venues',
  data: {
    datatable: TabularTables.Venues
  }
});
````

Template HTML:
````
<template name="main">
    <h1>Header</h1>
    {{> tabular table=datatable class="ui table"}}
    <h3>Footer</h3>
</template>
````

Problem is when changing routes (i.e. navigating from "orders" to "venues" or vice versa, the datable won't reload and shows blank on the subsequent route. Is there a way to force-reload the table when switching routes?

Note that manually refreshing the page in the browser fixes the issue.

**Comment by shilman** [comment] 2015-03-03 23:32
I am having the same problem. Here is a simple repro in Meteorpad:

http://meteorpad.com/pad/uEYCDZTn8Y6afS3KT/Tabular

Click on `Foos` link to see the Foos table. Click on `Bars` and the table should update with the Bars data, but doesn't. Behavior in Meteorpad is slightly different compared to when I run it locally, but neither do what I expect.

I have poked around a little bit and found:
 - `tableInit` is being called with what appear to be the correct arguments
 - `table.ajax.reload(null, true);` is being called as well

However, the table is not redrawing properly. I tried various things like `table.clear()` / `table.destroy()` / `Meteor.defer` but didn't have any success.

**Comment by ajlin500** [comment] 2015-03-09 17:41
Anyone have any luck with this? I have been poking around trying to debug it and have gotten no where

**Comment by raedle** [comment] 2015-03-17 20:24
I'd also be interested in a solution or workaround.

**Comment by boustanihani** [comment] 2015-03-25 00:39
Duplicate of: https://github.com/aldeed/meteor-tabular/issues/85

**Comment by boustanihani** [comment] 2015-03-25 01:50
It seems that ```aldeed:tabular``` is getting into some illegal state, when the ```Tabular.Table``` instance is changed dynamically.

**As a temporary workaround**, I am forcing the table to reinitialize by letting Blaze rerender it on each route change. **I am calling ```forceReRender()``` on all routes that display tables**, here is my code:

```javascript
var timeoutHandle, waiting = new ReactiveVar('false');

forceReRender = function() {

    timeoutHandle && Meteor.clearTimeout(timeoutHandle);

    waiting.set(true);

    timeoutHandle = Meteor.setTimeout(function() {
        waiting.set(false);
        timeoutHandle = null;
    }, 100); // Wait for 100 ms
};

Template.registerHelper('forceReRender', function() {
    return !waiting.get();
});
```

```
{{#if forceReRender}}
    {{> tabular table=MyTabularTable class="table table-striped table-condensed"}}
{{/if}}
```

**Comment by aldeed** [comment] 2016-01-08 17:58
Pretty sure this was fixed at some point since I currently hot swap table prop between routes without issue in one app I work on.

**Closed by aldeed** 2016-01-08 17:58 UTC
