### ISSUE TITLE
2 small issues

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-tabular#28] opened 2015-01-03 13:52 UTC
@aldeed Awesome work man, I discovered this package yesterday :)

I just noticed 2 small issues:

1) Suppose we have 30 documents and we are showing 10 documents per page. Suppose we navigate to page 2 and then choose to show 100 documents per page, the documents from the first page will be missing and we will only see the rest 20 documents. (The pagination will also be showing one page, as if there were no other docs/pages to show). As a fix I suggest to always reset the cursor when the number of docs per page changes.

2) If we set ```orderable:false``` on the **_id field** (```data:"_id"```) the ordering icon appears when the table is loaded for the first time and then disappears when ordering any other column.

**Comment by yuomtheara** [comment] 2015-01-05 00:55
i have the same problem.

**Comment by aldeed** [comment] 2015-01-17 22:17
@boustanihani, these may be issues with DataTables itself I think. Can you test out using a DataTable directly? We can possibly override the behavior of the first one, but I'm trying to avoid doing anything too opinionated in this package.

Also 1.0 is released, though I verified that these are still issues. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.

**Comment by boustanihani** [comment] 2015-01-18 21:48
@aldeed I just tested the first issue directly on the official datatables page (http://datatables.net/) and it seems to be working fine.

Just look at the data, then switch to page 2 then choose to show 100 entries instead of 10, you will notice that the cursor is reset and you will see all 57 entries and the pagination is also recalculated and shows only 1 of 1 pages, so I guess its a meteor-tabular issue.

**Comment by aldeed** [comment] 2015-01-19 13:04
I was able to reproduce, I just couldn't figure out how it could be related to tabular since datatables is handling all the paging logic. Although now I'm thinking maybe it's a side effect of the logic I added to retain the current page on hot code push.

**Comment by aldeed** [comment] 2015-01-19 13:39
I verified that datatables is actually requesting the wrong start value in the ajax function, but I'm not sure why it's doing that. [Their ajax example](http://www.datatables.net/examples/data_sources/server_side.html) works properly, so there must be something different with the way the table is set up in tabular.

**Comment by aldeed** [comment] 2015-01-19 13:51
Oh, I guess the fact that I'm passing `resetPaging` as `false` when triggering the ajax reload might have something to do with it. :) Shouldn't be too hard to fix that logic.

**Comment by aldeed** [comment] 2015-01-20 04:32
Opened #48 for your second issue. The first issue is fixed in v1.0.4.

**Closed by aldeed** 2015-01-20 04:32 UTC
Labels: potential bug
