### ISSUE TITLE
Loading symbol while waiting for data?

### ISSUE THREAD

**Issue by vicusbass** [aldeed/meteor-tabular#150] opened 2015-05-25 18:41 UTC
Is there any way to render a loading template (or a basic loading spinner) while data is being loaded? I suppose it should be a trick regarding some DataTables callback, but I have no clue. Any suggestions please?

**Comment by AdamBrodzinski** [comment] 2015-06-20 15:57
+1, Perhaps i'll submit a PR for this soon.

**Comment by abhirakshit** [comment] 2015-07-04 09:58
+1 Would love to have this feature.

**Comment by suryaiiit** [comment] 2015-07-16 13:05
+1

**Comment by joshperrin** [comment] 2015-07-22 23:55
+1

**Comment by Ossip** [comment] 2015-08-11 18:47
+1

**Comment by AdamBrodzinski** [comment] 2015-08-11 22:31
I ended up needing to hide the table while it was hiding so I started a spinner, tracked the collection the table uses, then on tracker change, stop the computation and clear the spinner. This switches the session var so the template unhides the table and shuts off the spinner.

**Comment by thearabbit** [comment] 2015-08-24 10:41
:+1:

**Comment by aldeed** [comment] 2015-09-02 17:41
Closing as duplicate of #130

**Closed by aldeed** 2015-09-02 17:41 UTC
