### ISSUE TITLE
Use array as data rather than collection

### ISSUE THREAD

**Issue by philipobrien** [aldeed/meteor-tabular#260] opened 2016-01-20 09:53 UTC
Say the collection I am trying to create a table from (MyCollection) has just a single object containing all the data, i.e. of the form

``` javascript
{
  input: Array[365],
  output: Array[365],
  date: Array[365]
}
```

If I follow the approach I am used to with tabular

``` javascript
TabularTables.MyTable = new Tabular.Table({
    name: "MyTable",
    collection: MyCollection,
    columns: [
        {data: "input", title: "Input", searchable: false},
        {data: "output", title: "Output", searchable: false},
        {data: "date", title: "Date", searchable: false}
    ],
    order: [[1, "desc"]],
    pageLength: 10
});
```

all 365 elements of each variable end up in a single cell, so I have one massive row, whereas I want each element to be created in a separate row i.e.

```
Input      Output      Date
input[0]   output[0]   date[0]
input[1]   output[1]   date[1]
```

I have tried returning an array rather than a collection like below, but can't get it to work

``` javascript
TabularTables.MyTable = new Tabular.Table({
    name: "MyTable",
    collection: function() { 
        var data = MyCollection.findOne();
        var list = [];
        for (var i in data.input) {
            list.push({
                input: data.input[i],
                output: data.output[i],
                date: data.date[i]
            });
        })
        return list;        
     }();
    });
```

Is the only solution to create a local collection from this array, as per [issue #58](https://github.com/aldeed/meteor-tabular/issues/58#issuecomment-131877734)?

**Comment by aldeed** [comment] 2016-10-30 22:09
Closing as duplicate of https://github.com/aldeed/meteor-tabular/issues/58

**Closed by aldeed** 2016-10-30 22:09 UTC
