### ISSUE TITLE
Show All option shows only one doc (instead of all docs)

### ISSUE THREAD

**Issue by AnnotatedJS** [aldeed/meteor-tabular#175] opened 2015-07-06 17:53 UTC
I added the following option to tabular:

    lengthMenu: [ [10, 20, 40, 100, -1], [10, 20, 40, 100, "All"] ],

However, the All option shows only one doc (instead of all docs)

The lengthMenu option is described at http://datatables.net/reference/option/lengthMenu

**Comment by aldeed** [comment] 2015-07-14 14:53
Duplicate of https://github.com/aldeed/meteor-tabular/issues/69

**Closed by aldeed** 2015-07-14 14:53 UTC
