### ISSUE TITLE
deletions by other users were not reactively reflected because of "flashing" check

### ISSUE THREAD

**Issue by jrmurad** [aldeed/meteor-tabular#87] opened 2015-03-01 02:05 UTC
I noticed that deletions by other users were not being reactively reflected. I believe this code in tabular.js is the culprit:

    // We're subscribing to the docs just in time, so there's
    // a good chance that they aren't all sent to the client yet.
    // We'll stop here if we didn't find all the docs we asked for.
    // This will rerun one or more times as the docs are received
    // from the server, and eventually we'll have them all.
    // Without this check in here, there's a lot of flashing in the
    // table as rows are added.
    if (cursor.count() < tableInfo.ids.length) {
      return;
    }

It may make sense when docs are expected to be added but not when they are removed?

(P.S. many thanks for your Meteor contributions, I take advantage of most of them)

**Comment by aldeed** [comment] 2015-09-11 13:00
Upon deletion I would think `tableInfo.ids` would be updated to not included the deleted ID, so the check would be fine. I will close this since it has probably been fixed, but if not please post a link to a simple app that reproduces the issue.

**Closed by aldeed** 2015-09-11 13:00 UTC
Labels: potential bug
