### ISSUE TITLE
How to search/sort on rendered field values?

### ISSUE THREAD

**Issue by glappen** [aldeed/meteor-tabular#132] opened 2015-04-30 20:45 UTC
First of all, awesome plugin - very very useful!

We have a table where some of the columns are directly rendered, and some use a function to render:

TabularTables.Meetings = new Tabular.Table
  name: "MeetingList"
  collection: Meetings
  columns: [
  {
      data: "programType"
      title: "Program Type"
    }
    {
      data: "chosenVenueNum"
      title: "City"
      render: (val, type, doc) -> doc.chosenVenue()?.city
    }
  ]

Searching for a Program Type value works, but searching for a City does not work - we get no search results.

Is there a way to have the datatable search work with rendered fields?  We have a similar problem with sorting due to the render function....

Thanks in advance for any suggestions.

**Comment by GenRMedia** [comment] 2015-05-01 02:53
I would also be interesting in any help with this issue...

**Comment by Deshtructioner** [comment] 2015-06-12 13:22
+1

**Comment by lance-anderson** [comment] 2015-06-22 21:38
+1

**Comment by illuminaut** [comment] 2015-07-03 20:52
+1

**Comment by illuminaut** [comment] 2015-07-04 00:53
also tried it with using a function for data attribute instead of render and same problem, searching doesn't work.

**Comment by glappen** [comment] 2015-07-06 14:38
In case this helps someone, I eventually gave up on this and we ended up storing all the fields (denormalized) in the collection so we could search and sort on them directly.  We used the collection hooks package to update the fields whenever a record is updated.

**Comment by mason505** [comment] 2015-08-07 20:53
+1

**Comment by tiomat** [comment] 2015-09-01 09:01
May be add some jQuery search on rendered table straight on page?

**Comment by aldeed** [comment] 2015-09-02 18:00
Closing as duplicate of #162. I'd like to find a solution.

**Closed by aldeed** 2015-09-02 18:00 UTC
