### ISSUE TITLE
Passing field/column to template

### ISSUE THREAD

**Issue by luixal** [aldeed/meteor-tabular#185] opened 2015-08-07 23:07 UTC
Hi, maybe this can be accomplished in another way, but I can't see how right now:

Let's say I want to include a template in a cell and reuse it in other columns (in my case, a green or red label according to the true/false value of current field in two different columns). Let an screenshot explain it better:

![image](https://cloud.githubusercontent.com/assets/615268/9147550/b90451a0-3d68-11e5-924c-4a1b407f2537.png)

Ok, for doing this, as both columns deppend on different object fields, I need to define two templates:

```html
<template name="incidencesFieldRead">
  <span class="label {{#if read}}label-success{{else}}label-danger{{/if}}"><b>{{#if isRead}}LEIDO{{else}}SIN LEER{{/if}}</b></span>
</template>

<template name="incidencesFieldSolved">
  <span class="label {{#if isSolved}}label-success{{else}}label-danger{{/if}}"><b>{{#if isSolved}}SOLUCIONADO{{else}}SIN SOLUCIONAR{{/if}}</b></span>
</template>
```
with two different helpers:

```javascript
Template.incidencesFieldRead.helpers({
  'isRead': function() {
    return this.read;
  }
});

Template.incidencesFieldSolved.helpers({
  'isSolved': function() {
    return this.solved;
  }
});
```
I'm  including this when creating the table:

```javascript
{
  data: 'read', title: 'Leído', tmpl: Meteor.isClient && Template.incidencesFieldRead
},
{
  data: 'solved', title: 'Solucionado', tmpl: Meteor.isClient && Template.incidencesFieldSolved
}
```

Because, on each template I do get the whole object, with no distinction.

Is there any way of getting just the value I want (I mean, always the same variable, maybe ```data``` with the value) or at least know the column index?

Thanks!

PS: By the way, I haven't been able to center the label inside the column, but that's another history.

**Comment by Ajaxsoap** [comment] 2015-08-09 14:22
I don't know if this will help but you may take a look at my approach:

**Helpers**
```
Template.status.helpers({
  statusPending: function() {
    if (this.status === 'Pending')
      return true;
    else
      return false;
  },
  statusApproved: function() {
    if (this.status === 'Approved')
      return true;
    else
      return false;
  },
  statusDenied: function() {
    if (this.status === 'Denied')
      return true;
    else
      return false;
  }
});
```
**Schema**
```
  status: {
    type: String,
    allowedValues: ['Pending','Approved','Denied']
  }
```
**Tabular**

```
{data:"status", title: "Status",
        tmpl: Meteor.isClient && Template.status
 }
```
 **Template**
```
<template name="status">
  {{#if statusPending}}
    <label class="btn btn-warning btn-xs">{{ status }}</label>
  {{/if}}

  {{#if statusApproved}}
    <label class="btn btn-primary btn-xs">{{ status }}</label>
  {{/if}}

  {{#if statusDenied}}
    <label class="btn btn-danger btn-xs">{{ status }}</label>
  {{/if}}
</template>
```

Cheers!

**Comment by luixal** [comment] 2015-08-09 15:57
Yes, that's another way of doing it, but you still need to hardcode each
case. Imagine you have like... 100 statuses, you'll have to do a lot of
boiler plate code. If you could get the individual field/column, you're
template would be much simpler, wouldn't it?

**Comment by Ajaxsoap** [comment] 2015-08-09 16:33
Yup, I agree, my code is actually a quick workaround and considering I only have few of this requirements. Things can get messy if you have a lot of this requirements.

**Comment by aldeed** [comment] 2015-09-02 17:11
Duplicate of https://github.com/aldeed/meteor-tabular/issues/129. I will close and track there, but this should be possible to do.

**Closed by aldeed** 2015-09-02 17:11 UTC
